CXX=g++
CFLAGS=-pedantic-errors --std=c++98 -g -Wfatal-errors -Wall -Wextra -Werror
#SPATH=./src
#OPATH=./bin
ONAME=registor.out

default:
	${CXX} ${CFLAGS} *.cpp -o ${ONAME}

run: default
	./${ONAME}

