CXX=g++
CFLAGS=-pedantic-errors --std=c++98 -g -Wfatal-errors -Wall -Wextra -Werror
#SPATH=./src
#OPATH=./bin
#ONAME=snw

default:
	${CXX} ${CFLAGS} main.cpp computer.cpp program.cpp -o perfanal.out

run: default
	./perfanal.out

